### ISSUE TITLE
Trained model on COCO worse than curve displayed in README Image

### ISSUE THREAD

**Issue by zhaohui-yang** [1zb/pytorch-image-comp-rnn#2]
I trained the code on dataset COCO 2014 train which contained 82783 images, but achieved MS-SSIM =0.809 when bpp = 0.125 which is lower than the displayed Image MS-SSIM ~= 0.83 when bpp = 0.125.

I am wondering is the COCO dataset which I used different from the dataset you used ? Or do you have any suggestions? 
Another question is that can I shorten the milestones and improve the learning rate?

In the origin paper, for JPEG420, bpp = 0.125, the MS-SSIM ~= 0.71, but in the README file, bpp = 0.125, jpeg file MS-SSIM ~= 0.8, are there any settings I haven't noticed yet?

**Comment by 1zb** [comment]
The COCO dataset should be the same. And the convergence is rather slow. Try my [trained model](https://github.com/1zb/pytorch-image-comp-rnn/releases).

**Comment by anishCFC** [comment]
Can we use jpg images of coco dataset for training or should we convert them to png images

**Comment by 1zb** [comment]
You can use images of [any format](https://github.com/1zb/pytorch-image-comp-rnn/blob/980f2ff6733c37ca0f4ecce9685a78fd873b2b3c/dataset.py#L30), as long as it is supported by `pillow`.

**Comment by vsag** [comment]
@1zb which coco dataset did you use?

**Comment by zhaohui-yang** [comment]
@1zb I have tested your pretrained model, which result in higher precision than the paper and your README file.

Whole kodak dataset MS-SSIM is 0.8395

For Image 10 in your README file, MSSSIM are:
0.875007 | 0.942168 | 0.96682 | 0.97744 | 0.982833 | 0.986212 | 0.988466 | 0.99023 | 0.991522 | 0.992443 | 0.993297 | 0.994 | 0.994585 | 0.994964 | 0.995358 | 0.995692

Thank you for your sharing!

**Comment by zhaohui-yang** [comment]
I found that batchsize is a parameter that effect a lot.

batchsize = 192, epoch = 50, msssim:
0.817116847	0.898990316	0.934607975	0.95259745	0.962711281	0.96874513	0.974054278	0.978903675	0.980994683	0.983448984	0.985564304	0.987125194	0.988492505	0.989197765	0.9900118	0.990851488


batchsize = 128, epoch = 50, msssim:
0.821909765	0.903733344	0.937065811	0.955193615	0.964337578	0.970245414	0.975407591	0.979637512	0.983130583	0.985118017	0.986603192	0.98791474	0.988783788	0.989728042	0.990737766	0.99158197


batchsize = 64, epoch = 50, msssim:
0.833470267	0.913988051	0.945007177	0.959452343	0.968072125	0.973665363	0.978204907	0.981892397	0.984217503	0.985769844	0.987485534	0.989085329	0.99013294	0.990938829	0.991613543	0.99234257

So, the original batchsize = 32 would fit for this. If larger batchsize is used, maybe decrease learning rate would be better.

**Comment by zhaohui-yang** [comment]
batchsize = 32, epoch = 50, msssim:

0.840983735	0.917781441	0.946476166	0.960836946	0.969941638	0.975545799	0.979455099	0.982536288	0.984690232	0.986649782	0.988325952	0.989746131	0.990785255	0.991577379	0.992198224	0.992711485

**Comment by lilala0** [comment]
@zhaohui-yang  Excuse me,i would like to ask you that the value of batchsize you changed is in which file
 .py？

**Comment by lilala0** [comment]
When i run the encoder.py ,i meet a " RuntimeError: CUDA error: out of memory". But i think my GPU is big enough because my GPU is 2G, so what shoud i do to deal with the issue?

**Comment by myaolee** [comment]
@zhaohui-yang 
Excuse me? I would like to ask you two questions as bellow:
1、 Have you ever met a question that "out of memory" when test the original Kodim10.png ? But if i turn the picture smaller the question would be solved. So i want to ask you whether you have met the question and how did you do to solve the question?
2、The binary stream after encoded and  binaried contain 16 pictures，so how did you calculation the bpp of one image ?

**Comment by lilala0** [comment]
> batchsize = 32, epoch = 50, msssim:
> 
> 0.840983735	0.917781441	0.946476166	0.960836946	0.969941638	0.975545799	0.979455099	0.982536288	0.984690232	0.986649782	0.988325952	0.989746131	0.990785255	0.991577379	0.992198224	0.992711485

@zhaohui-yang
Excuse me? I would like to ask you two questions as bellow:
1、 Have you ever met a question that "out of memory" when test the original Kodim10.png ? But if i turn the picture smaller the question would be solved. So i want to ask you whether you have met the question and how did you do to solve the question?
2、The binary stream after encoded and binaried contain 16 pictures，so how did you calculation the bpp of one image ?

**Comment by lilala0** [comment]
> I trained the code on dataset COCO 2014 train which contained 82783 images, but achieved MS-SSIM =0.809 when bpp = 0.125 which is lower than the displayed Image MS-SSIM ~= 0.83 when bpp = 0.125.
> 
> I am wondering is the COCO dataset which I used different from the dataset you used ? Or do you have any suggestions?
> Another question is that can I shorten the milestones and improve the learning rate?
> 
> In the origin paper, for JPEG420, bpp = 0.125, the MS-SSIM ~= 0.71, but in the README file, bpp = 0.125, jpeg file MS-SSIM ~= 0.8, are there any settings I haven't noticed yet?

Excuse me? I would like to ask you two questions as bellow:
1、 Have you ever met a question that "out of memory" when test the original Kodim10.png ? But if i turn the picture smaller the question would be solved. So i want to ask you whether you have met the question and how did you do to solve the question?
2、The binary stream after encoded and binaried contain 16 pictures，so how did you calculation the bpp of one image ?

**Comment by zhaohui-yang** [comment]
@lilala0 Hi,
For the first question, I haven't met the out of memory question, and my GPU memory is 12G. For the lastest version pytorch, you could try test with 
```
with torch.no_grad():
    run test code
```

For the second question, there is a csv file in test folder, you could see details in each line.

**Comment by myaolee** [comment]
@zhaohui-yang 
ok ,fine~. thank you so much for your reply.
