### ISSUE TITLE
RuntimeError: function SignBackward returned an incorrect number of gradients

### ISSUE THREAD

**Issue by sihuiluo** [1zb/pytorch-image-comp-rnn#4]
Hi, I'm new to pytorch and met an error when implement your code on pytorch 0.2.0:

File "train.py", line 164, in <module>
    loss.backward()
File"home/disk1/anaconda2/envs/python3/lib/python3.6/site-packages/torch/autograd/variable.py", line 156, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
RuntimeError: function SignBackward returned an incorrect number of gradients (expected 2, got 1)

Could you tell me how to fix this issue? Thx!

**Comment by sihuiluo** [comment]
I have fixed it

**Comment by MachineryZ** [comment]
how do you fix it? is it the input image's problem?

**Comment by MachineryZ** [comment]
i have the exactly same problem

**Comment by 1zb** [comment]
Sorry for the late replay. It seems caused by #1. Try modifying [this line](https://github.com/1zb/pytorch-image-comp-rnn/blob/master/functions/sign.py#L28) to 
```python
return grad_output, None
```

**Comment by orm011** [comment]
@1zb, that suggestion works, thanks.
