### ISSUE TITLE
train.py script fails at loss.backward

### ISSUE THREAD

**Issue by orm011** [1zb/pytorch-image-comp-rnn#5]
I'm running this as of
commit 7c49309df4e67b989eb8b4fa2ce3086136e49143
Date:   Tue Nov 14 10:36:23 2017 +0300

`python --version`
Python 3.5.4
`python -c 'import torch; print(torch.__version__)'`
0.2.0_3

# in particular i used this version
`pip install http://download.pytorch.org/whl/cu80/torch-0.2.0.post3-cp35-cp35m-manylinux1_x86_64.whl`

# when following directions on the readme, I run into:
 ```
python train.py -f /.../coco/train2017/
total images: 118287; total batches: 3697
Traceback (most recent call last):
  File "train.py", line 161, in <module>
    loss.backward()
  File "/home/orm/anaconda3/envs/py35torch02/lib/python3.5/site-packages/torch/autograd/variable.py", line 156, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/orm/anaconda3/envs/py35torch02/lib/python3.5/site-packages/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
RuntimeError: function SignBackward returned an incorrect number of gradients (expected 2, got 1)
```

**Comment by lixinfan** [comment]
HI orm,  have you fixed the error?     
I actually run into the same issue, and would like to know your solutions if any.  
Thanks in advance.

**Comment by 1zb** [comment]
@lixinfan 
Check new commit.
