### ISSUE TITLE
I fount it is very very slow to encode and decode

### ISSUE THREAD

**Issue by RangerWolf** [1zb/pytorch-image-comp-rnn#7]
Also encounter out of memory exception when add `--cuda` flag
I am using 1080Ti

is this normal?

**Comment by bupthyf** [comment]
> Also encounter out of memory exception when add `--cuda` flag
> I am using 1080Ti
> 
> is this normal?

Hello, I also encountered this problem. How did you solve this problem?

**Comment by RangerWolf** [comment]
> > Also encounter out of memory exception when add `--cuda` flag
> > I am using 1080Ti
> > is this normal?
> 
> Hello, I also encountered this problem. How did you solve this problem?

NO, I did not resolve this.  Shame to give it up.

**Comment by QingLicsaggie** [comment]
we can reduce memory based on this https://stackoverflow.com/questions/54374935/how-to-fix-this-strange-error-runtimeerror-cuda-error-out-of-memory
